version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
<<<<<<< HEAD
      - maven/test # checkout, build, test, and upload test results
=======
      - maven/test # checkout, build, test, and upload test results
>>>>>>> origin/master
